# -*- coding: utf-8 -*-
"""Midterm_Dopkins_Jennifer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19KzxeZR8LKm0tJnZ7f-5a5vbcaEPTeR1
"""

"""Question 1 """
f = open("numbers.txt", "r")
data = f.read()
for char in '-.,\n':
    data = data.replace(char,' ')
data = data.lower()
number_list = data.split()

d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
    print("{}: {}".format(key,value))
    print(f'{key} occurs {value} times')

import matplotlib.pyplot as plt
import numpy as np 
x = number_list
plt.figure(figsize=(15,4))
plt.hist(x)
plt.show()

import json
forj = d
y =json.dumps(forj)
print(y)

"""Question 2. Most common words"""
x = open("netflixdata.txt")
netflixdata = x.read()
for char in '1234567890:()-.,\n':
    netflixdata = netflixdata.replace(char,' ')
netflixdata = netflixdata.lower()
number_list = netflixdata.split()

d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
    if value > 2:
      print("{}: {}".format(key,value))

"""Question 2. Top 10 most common characters including numbers- bar graph"""
x = open("netflixdata.txt")
netflixdata = x.read()
for char in ':()-.,\n':
    netflixdata = netflixdata.replace(char,' ')
netflixdata = netflixdata.lower()
number_list = netflixdata.split()

d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
    if value > 100:
      print("{}: {}".format(key,value))

import matplotlib.pyplot as plt
import numpy as np 
x = np.array(['latest', 'charlie', '2013', '03', '0', 'season', 'episode', 'mac', 'not', 'view', 'us', 'united', 'states', '21', 'the', 'office', 'u', 's'])
y = np.array([174, 200, 200, 223, 444, 195, 195, 175, 173, 173, 200, 200, 200, 130, 193, 138, 137, 137])
plt.figure(figsize=(20,4))
plt.bar(x, y)
plt.show()

"""Question 2. Monthly viewing - line graph"""
x = open("netflixdata.txt")
netflixdata = x.read()
for char in '().,\n':
    netflixdata = netflixdata.replace(char,' ')
netflixdata = netflixdata.lower()
number_list = netflixdata.split()



date = '2013-03-20'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))

date = '2013-03-19'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))

date = '2013-03-18'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))



date = '2013-03-17'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))



date = '2013-03-16'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))

date = '2013-03-15'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))

date = '2013-03-14'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))

date = '2013-03-13'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))

date = '2013-03-12'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))

date = '2013-03-11'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))

date = '2013-03-10'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))

date = '2013-03-09'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))

date = '2013-03-08'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))

date = '2013-03-07'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))


date = '2013-03-06'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))


date = '2013-03-05'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))


date = '2013-03-04'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))


date = '2013-03-03'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))


date = '2013-03-02'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))


date = '2013-03-01'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == date:
        print("{}: {}".format(key,value))

import matplotlib.pyplot as plt
import numpy as np 
x = np.array(['2013-03-20', '2013-03-19', '2013-03-18', '2013-03-17', '2013-03-16', '2013-03-15', '2013-03-14', '2013-03-13', '2013-03-12', '2013-03-11', '2013-03-10', '2013-03-09', '2013-03-08', '2013-03-07', '2013-03-06', '2013-03-05', '2013-03-04', '2013-03-03', '2013-03-02', '2013-03-01' ])
y = np.array([5, 2, 17, 4, 14, 15, 10, 15, 22, 16, 15, 20, 4, 6, 8, 7, 4, 9, 3, 4])
plt.figure(figsize=(30,4))
plt.plot(x, y)
plt.show()

"""Question 2. TV show comparison - bar graph"""
x = open("netflixdata.txt")
netflixdata = x.read()
for char in '().,\n':
    netflixdata = netflixdata.replace(char,' ')
netflixdata = netflixdata.lower()
number_list = netflixdata.split()



show = 'star'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == show:
        print("{}: {}".format(key,value))

show = 'office'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == show:
        print("{}: {}".format(key,value))

show = 'archer'
d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == show:
        print("{}: {}".format(key,value))

import matplotlib.pyplot as plt
import numpy as np 
x = np.array(['star trek', 'the office', 'archer' ])
y = np.array([43, 138, 10])
plt.figure(figsize=(20,4))
plt.bar(x, y)
plt.show()

"Question 2. Devices comoparison - pie chart"
x = open("netflixdata.txt")
netflixdata = x.read()
for char in '()-.,\n':
    netflixdata = netflixdata.replace(char,' ')
netflixdata = netflixdata.lower()
number_list = netflixdata.split()


d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == 'xbox':
        print("{}: {}".format(key,value))

d = {}
for i in number_list: 
    d[i] = d.get(i, 0) + 1
for key, value in d.items():
      if key == 'mac':
        print("{}: {}".format(key,value))


import matplotlib.pyplot as plt
import numpy as np 
y = np.array([18, 175])
mylabels = ('xbox', 'mac')
plt.pie(y, labels = mylabels)
plt.show()